import type { Operation } from "@hermes-studio/protocol";
import type { RuntimeMessage } from "./i18n";

export type ProfileStatus = "working" | "waiting" | "idle" | "blocked";

export type Profile = {
  id: string;
  name: string;
  /** Optional local display alias kept by the Studio client. */
  displayName?: string | undefined;
  /** @deprecated Prefer displayName. Kept for demo data migration. */
  nameJa?: string | undefined;
  role: string;
  status: ProfileStatus;
  color: string;
  sessions: number;
  taskCount: number;
  memoryBytes: number;
  memoryNote: string;
  skills: string[];
  inheritedSkills: string[];
};

export type ChatMessage = {
  id: string;
  /** Monotonic order shared with operation evidence inside one session. */
  timelineSequence?: number | undefined;
  from: "user" | "agent" | "tool";
  kind?: "steer" | undefined;
  body: string;
  /** Locale-neutral copy generated by Studio itself. Hermes-provided text stays in body. */
  presentation?: { kind: "tool-fallback"; name?: string | undefined; phase: "running" | "complete" } | undefined;
  at: string;
  status?: "streaming" | "complete" | "failed" | "cancelled";
  /** Legacy in-memory shape migrated into ChatSession.operationEvidence before transcript replacement. */
  promptOperation?: {
    id: string;
    state: "pending" | "accepted" | "rejected" | "unconfirmed";
    message?: string | undefined;
  } | undefined;
};

export type ChatOperationEvidence = {
  id: string;
  /** Monotonic order shared with transcript messages inside one session. */
  timelineSequence?: number | undefined;
  kind: "prompt" | "steer";
  body: string;
  at: string;
  state: "pending" | "accepted" | "rejected" | "unconfirmed";
  message?: string | undefined;
};

export type ChatConnectionState = "disconnected" | "connecting" | "queued" | "ready" | "error";
export type ChatHistoryState = "unloaded" | "loading" | "loaded" | "error";

export type ApprovalChoice = "once" | "session" | "always" | "deny";

export type ChatPendingInteraction =
  | {
      id: string;
      kind: "clarify";
      requestId: string;
      question: string;
      choices: string[];
      submitting: boolean;
      error?: RuntimeMessage | undefined;
    }
  | {
      id: string;
      kind: "approval";
      approvalId: string;
      command?: string | undefined;
      description?: string | undefined;
      choices: ApprovalChoice[];
      allowPermanent: boolean;
      submitting: boolean;
      error?: RuntimeMessage | undefined;
    };

export type ChatSession = {
  /** Stable UI identity. It can exist before Hermes persists a session. */
  id: string;
  /** Durable Hermes state.db identity used by REST history and resume. */
  storedSessionId?: string | undefined;
  /** Process-local gateway identity, valid only for the current WebSocket. */
  liveSessionId?: string | undefined;
  profileId: string;
  title: string;
  /** Only local draft titles are translated at render time. Hermes titles remain verbatim. */
  titlePresentation?: "new-chat" | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  lastMessagePreview?: string | undefined;
  /** Studio-visible origin. Delegated chats are durable worker conversations. */
  conversationKind?: "direct" | "delegated" | undefined;
  /** Shared Kanban task that created a delegated profile conversation. */
  delegationTaskId?: string | undefined;
  /** Profile that created the delegated task, when known. */
  delegatedByProfileId?: string | undefined;
  status: "streaming" | "ready" | "waiting";
  messages: ChatMessage[];
  /** Bounded local RPC evidence. It is deliberately separate from Hermes' durable transcript. */
  operationEvidence?: ChatOperationEvidence[] | undefined;
  connectionState?: ChatConnectionState;
  historyState?: ChatHistoryState;
  historyPartial?: boolean;
  historyNotice?: RuntimeMessage | undefined;
  errorMessage?: RuntimeMessage | undefined;
  remoteKind?: "demo" | "stored" | "draft" | undefined;
  streamingMessageId?: string | undefined;
  /** Upstream identity for streamingMessageId; separate from its unique UI id. */
  streamingSourceMessageId?: string | undefined;
  /** Completed interim assistant rows created during the current run only. */
  interimMessageIds?: string[] | undefined;
  /** True after the run's first assistant frame until its terminal fence. */
  chatRunStarted?: boolean | undefined;
  /** Server-assigned occurrence identity for the active assistant run. */
  chatRunId?: string | undefined;
  /** Process-unique server correlation epoch for sequence comparisons. */
  chatCorrelationEpoch?: string | undefined;
  /** Server sequence for the active assistant run. */
  chatRunServerSequence?: number | undefined;
  /** High-water mark for terminal runs; rejects every older run without an LRU window. */
  completedChatRunServerSequence?: number | undefined;
  /** High-water mark for delivered gateway events; makes replay rejection independent of count. */
  processedChatEventSequence?: number | undefined;
  /** Upstream assistant identity retained even while no stream bubble is open. */
  chatRunSourceMessageId?: string | undefined;
  /** Monotonic client-side occurrence number advanced by a run's first assistant frame. */
  chatRunSequence?: number | undefined;
  /** Recent upstream tool occurrences used to distinguish reuse from replay. */
  toolMessageBindings?: Array<{
    runSequence: number;
    sourceId: string;
    messageId: string;
  }> | undefined;
  pendingInteraction?: ChatPendingInteraction | undefined;
  steerPending?: boolean | undefined;
  steerOperationId?: string | undefined;
  interruptPending?: boolean | undefined;
  interruptOperationId?: string | undefined;
  slashPending?: boolean | undefined;
  slashOperationId?: string | undefined;
  composerPrefill?: { id: string; text: string } | undefined;
  readOnly?: boolean;
  /** Preferred model for session.create / display. */
  model?: string | undefined;
  /** Preferred provider for session.create / display. */
  provider?: string | undefined;
  /** Preferred reasoning_effort for new Hermes sessions (omit when empty/default). */
  reasoningEffort?: string | undefined;
  /**
   * Deferred model switch: staged when the user picks a model mid-session and
   * sent as a /model command right before the next outbound prompt.
   * `baseline` remembers the prefs before the first staged pick so re-selecting
   * the original model cancels the pending switch.
   */
  pendingModelChange?: {
    command: string;
    reasoningCommand?: string | undefined;
    model: string;
    applying?: boolean;
    /** The model RPC settled successfully; only the reasoning follow-up remains. */
    modelApplied?: boolean;
    baseline: { provider?: string | undefined; model?: string | undefined; reasoningEffort?: string | undefined };
  } | undefined;
  /** Local follow-up chips after the latest assistant reply. */
  followUpSuggestions?: string[] | undefined;
  /**
   * Studio client link: this chat was opened from a Kanban card ("Ask assignee").
   * Not a Hermes durable identity; used for reuse and chrome only.
   */
  sourceCardId?: string | undefined;
  sourceCardTitle?: string | undefined;
  /** One-shot guard so card context is attached only to the first user-authored prompt. */
  sourceCardSeeded?: boolean | undefined;
  /** Card context for the first user-authored prompt; never auto-sent. */
  pendingCardSeed?: string | undefined;
};

export type TaskStatus = "triage" | "todo" | "scheduled" | "ready" | "running" | "blocked" | "review" | "done" | "archived";
export type TaskWritableStatus = "triage" | "todo" | "scheduled" | "ready" | "blocked" | "done" | "archived";

export type WorkTask = {
  id: string;
  title: string;
  body?: string | undefined;
  status: TaskStatus;
  assigneeId?: string | undefined;
  priority: "normal" | "high";
  priorityValue?: number;
  comments: number;
  latestSummary?: string | undefined;
  pending?: boolean;
};

export type TaskComment = {
  id: number;
  cardId: string;
  author: string;
  body: string;
  createdAt: number;
};

export type KanbanConnectionState = "idle" | "loading" | "ready" | "saving" | "error";

export type Surface = "office" | "kanban" | "teams" | "library" | "settings" | "scheduled";
export type InspectorTab = "chat" | "profile" | "skills" | "memory";
export type SettingsTab = "global" | "project" | "skills" | "soul" | "memory" | "config" | "privileged" | "host";

export type OfficeConnectionState = "demo" | "connecting" | "connected" | "degraded" | "error";
export type OfficeAccessState = "checking" | "login-required" | "submitting" | "authenticated" | "unavailable";

export type OfficeAccess = {
  state: OfficeAccessState;
  serverUrl: string;
  message: RuntimeMessage;
  failureCode?: "invalid" | "rate-limited" | "disabled" | "unavailable" | undefined;
  retryAfterSeconds?: number | undefined;
};

export type OfficeRuntimeState =
  | "unconfigured"
  | "starting"
  | "ready"
  | "stopping"
  | "stopped"
  | "unreachable"
  | "incompatible"
  | "error";

export type OfficeConnection = {
  state: OfficeConnectionState;
  source: "demo" | "server";
  serverUrl: string;
  runtime?: OfficeRuntimeState;
  protocolVersion?: number;
  generatedAt?: string;
  eventStream: "closed" | "connecting" | "open";
  message: RuntimeMessage;
};

export type OfficeSnapshotProfile = {
  id: string;
  name: string;
  activity: string;
  activeSessionCount: number;
};

export type OfficeInventoryPagination = {
  returned: number;
  available: number;
  total?: number;
  hasMore: boolean;
  truncated: boolean;
  partialFailures: number;
  nextCursor?: string;
};

export type OfficeSnapshot = {
  generatedAt: string;
  sequence: number;
  capabilities: {
    protocolVersion: number;
    serverVersion: string;
    runtime: { state: OfficeRuntimeState; hermesVersion?: string; adapterVersion?: string };
    access: {
      deviceId: string;
      tier: "viewer" | "operator" | "manager" | "owner";
      exposure: "loopback" | "tailnet" | "public";
      authentication: "desktop-capability" | "local-cookie" | "device-cookie" | "tailscale-identity" | "oidc";
      allowedOperations: Operation[];
    };
    features: Array<"chat" | "profiles" | "skills" | "memory" | "kanban" | "teams" | "global-inheritance" | "demo">;
  };
  profiles: OfficeSnapshotProfile[];
  sessions: Array<{ id: string; profileId: string; title: string; activity: string; createdAt?: string; updatedAt?: string; lastMessagePreview?: string; conversationKind?: "direct" | "delegated"; delegationTaskId?: string; delegatedByProfileId?: string }>;
  inventory: { profiles: OfficeInventoryPagination; sessions: OfficeInventoryPagination };
  boards: Array<{ id: string; name: string; cardCount: number }>;
};

export type OfficeSnapshotRequestIdentity = Readonly<{
  serverUrl: string;
  connectionGeneration: number;
  requestGeneration: number;
}>;
